ControlFocus("Open","","Edit1")
Sleep(1000)
ControlSetText("Open","","Edit1","C:\Users\ASUS\Downloads\reasoning.pdf")
Sleep(1000)
ControlFocus("Open","","Button1")
Sleep(1000)
ControlClick("Open","","Button1")